<?php

namespace Tests\Feature;

use App\Models\Community;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class CommunitiesTest extends TestCase
{
    protected $user;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->user = User::factory()->create();

        $this->actingAs($this->user);

        $this->form = [
            "title" => "테스트",
            "description" => "테스트",
            "url" => "https://naver.com",
        ];
    }

    /** @test */
    public function 사용자는_커뮤니티를_생성요청할_수_있다()
    {
        $this->post("/api/communities", $this->form);

        $this->assertCount(1, Community::get());
    }
}
