<?php

namespace Tests\Feature;

use App\Models\Board;
use App\Models\Comment;
use App\Models\Like;
use App\Models\Post;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class LikesTest extends TestCase
{
    use RefreshDatabase;

    protected $user;
    protected $other;
    protected $post;
    protected $comment;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->user = User::factory()->create();
        $this->other = User::factory()->create();
        $this->post = Post::factory()->create();
        $this->comment = Comment::factory()->create();

        $this->actingAs($this->user);

        $this->form = [
            "comment_id" => $this->comment->id
        ];
    }

    /** @test */
    public function 좋아요를_생성하면_댓글의_좋아요수가_상승한다()
    {
        $this->post("/api/likes", $this->form);

        $comment = Comment::find($this->comment->id);
        $post = Post::find($this->post->id);

        $this->assertCount(1, Like::get());
        $this->assertEquals(1, $comment->count_like);
        $this->assertEquals(1, $post->count_like);
    }

    public function 좋아요를_생성하면_게시글의_좋아요수가_상승한다()
    {

    }

    public function 중복좋아요를_할_수_없다()
    {

    }
}
