<?php

namespace Tests\Feature;

use App\Models\Board;
use App\Models\Comment;
use App\Models\Report;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class ReportsTest extends TestCase
{
    use RefreshDatabase;

    protected $user;
    protected $form;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->user = User::factory()->create();

        $this->actingAs($this->user);

        $this->form = [
            "comment_id" => Comment::factory()->create()->id,
            "reason" => "테스트",
        ];
    }

    /** @test */
    public function 사용자는_댓글에_대한_신고를_생성할_수_있다()
    {
        $this->post('/api/reports', $this->form);

        $this->assertCount(1, Report::get());
    }
}
