<?php

namespace Tests\Feature;

use App\Models\Comment;
use App\Models\Hate;
use App\Models\Post;
use App\Models\Special;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class SpecialsTest extends TestCase
{
    use RefreshDatabase;

    protected $user;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->user = User::factory()->create();

        $this->actingAs($this->user);
    }

    /** @test */
    public function 누구나_스페셜목록을_조회할_수_있다()
    {
        $specials = Special::factory()->count(10)->create();

        $items = $this->get("/api/specials")->decodeResponseJson()["data"];

        $this->assertCount(count($specials), $items);

    }
}
