<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Like extends Model
{
    use HasFactory;

    protected $guarded = ["id", "user_id"];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::creating(function($model){
            $model->post_id = $model->comment->post_id;
        });

        self::created(function($model){
           $model->comment->update(["count_like" => $model->comment->count_like + 1]);
        });

        self::deleted(function($model){
            $model->comment->update(["count_like" => $model->comment->count_like - 1]);
        });
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function post()
    {
        return $this->belongsTo(Post::class);
    }

    public function comment()
    {
        return $this->belongsTo(Comment::class);
    }
}
