<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Visit extends Model
{
    use HasFactory;

    protected $guarded = ["id"];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::creating(function($model){
            if($model->post_id){
                $post = Post::find($model->post_id);

                if($post) {
                    $post->update(["count_view" => $post->count_view + 1]);

                    $model->board_id = $post->board_id;

                    $model->community_id = $post->board->community_id;
                }
            }
        });
    }
}
