<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Youtube extends Model
{
    use HasFactory;

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::creating(function($model){
            $model = $model->format();
        });

        self::updating(function ($model){
            $model = $model->format();
        });
    }

    public function format()
    {
        parse_str(parse_url($this->url, PHP_URL_QUERY), $params);

        if (isset($params["v"])) {
            $key = $params["v"];

            $this->key = $key;

            $this->thumbnail = "https://img.youtube.com/vi/".$key."/maxresdefault.jpg";
        }

        return $this;
    }
}
